name: Run Trading Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the Python version you need

      # Install dependencies (e.g., numpy, yfinance)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy yfinance pandas scikit-learn

      # Run your Python script
      - name: Run script
        run: |
          python main.py  # Replace with the actual script name
